# Generated by Django 4.0.6 on 2025-02-11 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carretera',
            name='longitud_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='carretera',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='carretera',
            name='tipo_superficie',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='constructora',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='constructora',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='proyectoinfraestructura',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
    ]
